version: '3'
services:
  rabbitmq-service:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
  data-service:
    build: ./data-service
    depends_on:
      - rabbitmq-service
  webhook-service:
    build: ./webhook-service
    depends_on:
      - rabbitmq-service
  inventory:
    build: 
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./inventory-service:/usr/src/app/src:z
    ports:
     - "5001:3001"
    depends_on:
      - rabbitmq-service
    restart: always

  shipping:
    build: 
      context: ./shipping-service
      dockerfile: Dockerfile
    container_name: shipping
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./shipping-service:/usr/src/app/src:z
    ports:
     - "5003:3002"
    depends_on:
      - rabbitmq-service
    restart: always

  users:
    build: 
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./users-service:/usr/src/app/src:z
    ports:
     - "5006:3003"
    depends_on:
      - rabbitmq-service
    restart: always
    
  billing:
    build: 
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./billing-service:/usr/src/app/src:z
    ports:
     - "5002:3000"
    depends_on:
      - rabbitmq-service
    restart: always
